/* MTI_DPI */

/*
 * Copyright 2002-2021 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_ELF
#define INCLUDED_ELF

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
const char*
Get_SRAM_ELF_object_filename();

DPI_LINK_DECL DPI_DLLESPEC
char
get_section(
    int64_t* address,
    int64_t* len);

DPI_LINK_DECL DPI_DLLESPEC
svLogic
read_elf(
    const char* filename);

DPI_LINK_DECL DPI_DLLESPEC
char
read_section(
    int64_t address,
    const svOpenArrayHandle buffer);

#endif 
